name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies for all workspaces
        run: npm ci

      - name: Build frontend
        run: npm run build --workspace=frontend

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Create directories on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }} "
            sudo mkdir -p /var/www/ildidev/portfolio-site-monorepo/{frontend/dist,backend} && 
            sudo chown -R ${{ secrets.DO_SSH_USER }}:${{ secrets.DO_SSH_USER }} /var/www/ildidev/portfolio-site-monorepo
          "

      - name: Copy root level files
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          --exclude 'node_modules' \
          --exclude '.git' \
          --exclude 'frontend/dist' \
          --exclude 'frontend/node_modules' \
          --exclude 'backend/node_modules' \
          ./ ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }}:/var/www/ildidev/portfolio-site-monorepo/

      - name: Copy frontend files to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          ./frontend/dist/ ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }}:/var/www/ildidev/portfolio-site-monorepo/frontend/dist/

      - name: Copy backend files to server
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          --exclude '.env' \
          --exclude 'node_modules' \
          --exclude 'config/serviceAccounts.json' \
          ./backend/ ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }}:/var/www/ildidev/portfolio-site-monorepo/backend/

      - name: Install production dependencies on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }} "
            cd /var/www/ildidev/portfolio-site-monorepo && 
            npm ci --production
          "

      - name: Restart server using PM2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }} "
            cd /var/www/ildidev/portfolio-site-monorepo && 
            pm2 reload all || pm2 restart all || true
          "

      - name: Verify deployment
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }} "
            echo 'Checking PM2 status...' && 
            pm2 list && 
            echo 'Checking directory structure...' && 
            ls -la /var/www/ildidev/portfolio-site-monorepo/
          "
